[package]
name = "ado-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
dirs = { workspace = true }
getrandom = { workspace = true }
keyring = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
ureq = { workspace = true, features = ["rustls"] }

[dev-dependencies]
ado-testkit = { path = "../ado-testkit" }
