[package]
name = "ado"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ado-core = { path = "../ado-core" }
clap = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
ado-testkit = { path = "../ado-testkit" }
assert_cmd = { workspace = true }
