//! `ado completion` — shell completion scripts generated from the clap tree and
//! emitted raw, with no envelope even under `--json` (spec §6.7).

use std::fs;
use std::io;
use std::path::Path;

use clap_complete::aot::{Bash, Fish, Generator, PowerShell, Zsh, generate};

use ado_core::error::AdoError;

use crate::cli;
use crate::output::Report;

/// The shells the positional argument accepts, in the order errors list them.
pub const SUPPORTED_SHELLS: [&str; 4] = ["bash", "zsh", "fish", "powershell"];

/// The shell used when the positional argument is omitted.
pub const DEFAULT_SHELL: &str = "bash";

pub fn run(shell: Option<&str>, write_to_file: Option<&Path>) -> Result<Report, AdoError> {
    let script = script_for(shell.unwrap_or(DEFAULT_SHELL))?;

    match write_to_file {
        Some(path) => {
            fs::write(path, script).map_err(|error| write_error(path, &error))?;
            Ok(Report::Text(String::new()))
        }
        None => Ok(Report::Raw(script)),
    }
}

fn script_for(shell: &str) -> Result<String, AdoError> {
    let script = match shell {
        "bash" => render(Bash),
        "zsh" => render(Zsh),
        "fish" => render(Fish),
        "powershell" => render(PowerShell),
        other => return Err(unknown_shell(other)),
    };

    Ok(with_header(shell, script))
}

/// clap_complete writes to any `io::Write`, so the script is generated into a
/// buffer and handed back to the caller as one string.
fn render(generator: impl Generator) -> String {
    let mut command = cli::command();
    let mut buffer = Vec::new();

    generate(generator, &mut command, "ado", &mut buffer);

    String::from_utf8_lossy(&buffer).into_owned()
}

/// The provenance line names the current invocation — `-s` is `--server`, not a
/// shell flag. In zsh it has to follow `#compdef`, which compinit only reads from
/// the first line of an autoloaded file.
fn with_header(shell: &str, script: String) -> String {
    let header = format!("# Generated by: ado completion {shell}\n");

    match script.split_once('\n') {
        Some((first, rest)) if first.starts_with("#compdef") => format!("{first}\n{header}{rest}"),
        _ => format!("{header}{script}"),
    }
}

fn unknown_shell(shell: &str) -> AdoError {
    AdoError::validation(format!(
        "Unknown shell '{shell}'. Must be one of: {}.",
        SUPPORTED_SHELLS.join(", ")
    ))
}

/// An unwritable path is command-level input to reject, like an unknown shell.
fn write_error(path: &Path, error: &io::Error) -> AdoError {
    AdoError::validation(format!(
        "Could not write the completion script to {}: {error}",
        path.display()
    ))
}
