//! `ado schema` — the CLI command tree, generated by walking the clap tree.

use clap::{Arg, ArgAction, Command};
use serde_json::{Value, json};

use ado_core::envelope::ok_named;
use ado_core::error::AdoError;

use crate::VERSION;
use crate::cli;
use crate::output::Report;

pub fn run(json: bool, target: Option<&str>) -> Result<Report, AdoError> {
    let mut tree = match target {
        Some(name) => find_node(name).ok_or_else(|| unknown_command(name))?,
        None => build_tree(),
    };

    if let Value::Object(node) = &mut tree {
        node.insert("version".to_owned(), json!(VERSION));
    }

    if json {
        Ok(Report::Json(ok_named("schema", tree)))
    } else {
        Ok(Report::Text(human(&tree)))
    }
}

/// The whole tree, rooted at `ado`.
pub fn build_tree() -> Value {
    node_to_json(&prepared_command(), "ado")
}

/// The node named by `name` and its descendants. `name` is a command or a
/// whitespace-separated path, with the leading `ado` optional: `version` and
/// `ado version` both resolve to the same node.
pub fn find_node(name: &str) -> Option<Value> {
    let mut segments = name.split_whitespace().peekable();
    let has_root_prefix = segments.peek() == Some(&"ado");

    if has_root_prefix {
        segments.next();
    } else if segments.peek().is_none() {
        return None;
    }

    let root = prepared_command();
    let mut command = &root;
    let mut path = String::from("ado");

    for segment in segments {
        let sub = command.find_subcommand(segment)?;
        path.push(' ');
        path.push_str(sub.get_name());
        command = sub;
    }

    Some(node_to_json(command, &path))
}

/// clap copies an argument declared `global(true)` into every subcommand while
/// building, so the tree has to be built before it is walked — that copy is what
/// puts the global options in every node.
fn prepared_command() -> Command {
    let mut command = cli::command();
    command.build();
    command
}

/// One node as JSON, named by its full command path (e.g. `ado version`).
/// Descendants are walked from `command` as it is handed over.
pub fn node_to_json(command: &Command, path: &str) -> Value {
    let subcommands = command
        .get_subcommands()
        .map(|sub| node_to_json(sub, &format!("{path} {}", sub.get_name())))
        .collect::<Vec<_>>();

    json!({
        "name": path,
        "doc": command.get_about().map(ToString::to_string).unwrap_or_default(),
        "arguments": arguments(command),
        "options": options(command),
        "subcommands": subcommands,
    })
}

fn arguments(command: &Command) -> Vec<Value> {
    command
        .get_arguments()
        .filter(|arg| arg.is_positional() && !is_display_action(arg))
        .map(|arg| {
            json!({
                "name": arg.get_id().as_str(),
                "type": type_of(arg),
                "required": arg.is_required_set(),
                "doc": doc_of(arg),
            })
        })
        .collect()
}

fn options(command: &Command) -> Vec<Value> {
    command
        .get_arguments()
        .filter(|arg| !arg.is_positional() && !is_display_action(arg))
        .map(|arg| {
            json!({
                "name": arg.get_id().as_str(),
                "short": arg.get_short().map(|short| short.to_string()).unwrap_or_default(),
                "type": type_of(arg),
                "default": default_of(arg),
                "required": arg.is_required_set(),
                "doc": doc_of(arg),
            })
        })
        .collect()
}

/// `--help` and `--version` print and exit; they are clap plumbing rather than
/// command surface, so they are not part of the tree.
fn is_display_action(arg: &Arg) -> bool {
    matches!(
        arg.get_action(),
        ArgAction::Help | ArgAction::HelpShort | ArgAction::HelpLong | ArgAction::Version
    )
}

/// Flags are `boolean`, everything that takes a value is `string`.
fn type_of(arg: &Arg) -> &'static str {
    if arg.get_action().takes_values() {
        "string"
    } else {
        "boolean"
    }
}

/// The declared default, stringified: flags read `false`, value-taking options
/// `""` when no default is declared.
fn default_of(arg: &Arg) -> String {
    match arg.get_default_values().first() {
        Some(value) => value.to_string_lossy().into_owned(),
        None if arg.get_action().takes_values() => String::new(),
        None => "false".to_owned(),
    }
}

fn doc_of(arg: &Arg) -> String {
    arg.get_help().map(ToString::to_string).unwrap_or_default()
}

fn unknown_command(name: &str) -> AdoError {
    AdoError::validation(format!(
        "no command named \"{name}\". Run `ado schema` to see all commands."
    ))
}

fn human(tree: &Value) -> String {
    let mut out = format!("ado v{VERSION} — command tree\n{}\n", "─".repeat(60));

    render_node(&mut out, tree, 0);
    out.push_str("\nRun with --json for a structured tree.\n");

    out
}

fn render_node(out: &mut String, node: &Value, depth: usize) {
    let indent = "  ".repeat(depth);

    out.push_str(&format!("{indent}{}\n", text(&node["name"])));

    let doc = text(&node["doc"]);

    if !doc.is_empty() {
        out.push_str(&format!("{indent}  {doc}\n"));
    }

    let options = as_array(&node["options"]);

    if !options.is_empty() {
        out.push_str(&format!("{indent}  options:\n"));

        for option in options {
            out.push_str(&format!("{indent}    {}\n", option_line(option)));
        }
    }

    let subcommands = as_array(&node["subcommands"]);

    if !subcommands.is_empty() {
        out.push_str(&format!("{indent}  subcommands:\n"));

        for sub in subcommands {
            render_node(out, sub, depth + 2);
        }
    }
}

fn option_line(option: &Value) -> String {
    let short = match text(&option["short"]) {
        "" => String::new(),
        short => format!(" -{short}"),
    };
    let default = match text(&option["default"]) {
        "" => String::new(),
        default => format!(" (default: {default})"),
    };

    format!(
        "--{}{short} <{}>{default}",
        text(&option["name"]),
        text(&option["type"]),
    )
}

fn as_array(value: &Value) -> &[Value] {
    value.as_array().map(Vec::as_slice).unwrap_or_default()
}

fn text(value: &Value) -> &str {
    value.as_str().unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn find_node_accepts_a_name_or_a_path() {
        assert_eq!(
            find_node("version").expect("the version node")["name"],
            json!("ado version")
        );
        assert_eq!(
            find_node("ado version").expect("the version node")["name"],
            json!("ado version")
        );
        assert_eq!(
            find_node("ado").expect("the root node")["name"],
            json!("ado")
        );
    }

    #[test]
    fn find_node_rejects_unknown_and_empty_names() {
        assert!(find_node("nope").is_none());
        assert!(find_node("version extra").is_none());
        assert!(find_node("").is_none());
        assert!(find_node("   ").is_none());
    }

    #[test]
    fn a_flag_reads_false_without_a_declared_default() {
        let command = Command::new("ado").arg(
            Arg::new("dry-run")
                .long("dry-run")
                .action(ArgAction::SetTrue),
        );

        let node = node_to_json(&command, "ado");
        let options = node["options"].as_array().expect("options");
        let dry_run = options
            .iter()
            .find(|option| option["name"] == json!("dry-run"))
            .expect("the dry-run option");

        assert_eq!(dry_run["default"], json!("false"));
        assert_eq!(dry_run["type"], json!("boolean"));
    }

    #[test]
    fn declared_defaults_and_required_are_read_from_the_argument() {
        let mut command = Command::new("ado")
            .arg(Arg::new("state").long("state").default_value("all"))
            .arg(Arg::new("name").required(true));
        command.build();

        let node = node_to_json(&command, "ado");
        let options = node["options"].as_array().expect("options");
        let state = options
            .iter()
            .find(|option| option["name"] == json!("state"))
            .expect("the state option");
        let arguments = node["arguments"].as_array().expect("arguments");

        assert_eq!(state["default"], json!("all"));
        assert_eq!(arguments[0]["name"], json!("name"));
        assert_eq!(arguments[0]["required"], json!(true));
    }
}
